name: hexo deploy

on:
  push:
    branches:
      - source
  schedule:
    - cron: "30 17 * * *"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    name: deploy gamelife1314.github.io

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Checkout private submodules(themes or something else).

      - name: Install Dependencies
        run: npm i
      
      - name: Github token install
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.GH_DEPLOY_PRI}}" >  ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Git config
        run: |
          git config --global user.name gamelife1314
          git config --global user.email 1185694600@qq.com

      - name: Generate and deploy
        run: |
          npm install -g hexo-cli
          hexo g
          hexo d

